### PR TITLE
Ruby 2.1.x chokes on quoted symbol in hash literal syntax

### PR DESCRIPTION
**Pull request by luismfonseca**
### What?

Using `=>` as opposed to `:`.

### Why?

My IDE didn't like it.

----

- [ ] CHANGELOG updated if relevant?

### CODE REVIEW

**Comment by mdpye** [comment]
That's the *old* syntax. Presumably your IDE doesn't cope with the case where the key has to be quoted, because `-` isn't allowed in symbol names.

I think you have changed the semantics, you want

```
  :"Content-Type" =>
```

(note the colon), otherwise you have changed the key type from symbol to string.

**Comment by mdpye** [comment]
Preferred solution: file bug against your IDE's ruby plugin ;)

```
irb(main):001:0> x = { "test-key": "value" }
=> {:"test-key"=>"value"}
irb(main):002:0> x = { "test-key" => "value" }
=> {"test-key"=>"value"}
irb(main):003:0> x = { :"test-key" => "value" }
=> {:"test-key"=>"value"}
irb(main):004:0> x = { test-key: "value" }
```

**Comment by luismfonseca** [comment]
I don't feel too strongly about it, might be a bug in the IDE 🤷‍♂

**Comment by mdpye** [comment]
Noticed that it's also a problem with the (long out of support) 2.1 parser: https://github.com/pusher/chatkit-server-ruby/issues/35

The fix seems harmless.

**Pull request merged**
