### PR TITLE
Api v2

### PR DESCRIPTION
**Pull request by vivangkumar**
### What?

v2 implementations

### Why?

Because v2.

----

- [ ] CHANGELOG updated if relevant?

### CODE REVIEW

**Comment by vivangkumar** [comment]
[[3] Ensure parameters read from URLs are always correctly decoded (v2)](https://trello.com/c/oexc1Crw/1240-3-ensure-parameters-read-from-urls-are-always-correctly-decoded-v2)

**Comment by hamchapman** [comment]
Does this automatically make multiple key value pairs in the query string then?

**Comment by vivangkumar** [comment]
Yeaaap, as discussed IRL.
https://github.com/excon/excon/pull/516

**Comment by vivangkumar** [comment]
That's a good idea. I'll do that and change the base branch.

**Comment by mdpye** [comment]
Closing this PR for now (as we don't want to merge it now)

**Pull request closed without merging**
