### PR TITLE
Api v2 string room ids

### PR DESCRIPTION
**Pull request by callum-oakley**
Tests need running against updated API when it's ready.

### CODE REVIEW

**Comment by mdpye** [comment]
Wrong base branch?

**Comment by callum-oakley** [comment]
Tests pass against development.

**Comment by mdpye** [comment]
Are we doing any URL encoding where appropriate?

**Comment by mdpye** [comment]
We should call this out explicitly in the changelog - the type system will not notify anyone of the expected change.

**Pull request merged**
